global:
  env: develop
  image:
    repository: hub.viewboost.vn/affiliate-products
    pullPolicy: Always
    tag: "latest"
  infisical_project_id: "e1418edd-82c7-46be-b653-3204d904e852"
  imagePullSecrets:
    - name: registry-affiliate-products
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-http-prod
    host:
      server_admin:
        host: api.toibit.dev
        path: /common/admin
        pathType: ImplementationSpecific
      server_public:
        host: api.toibit.dev
        path: /common/app
        pathType: ImplementationSpecific
      client:
        host: account.toibit.dev
        path: /
        pathType: ImplementationSpecific
      admin:
        host: admin.toibit.dev
        path: /account
        pathType: ImplementationSpecific