global:
  env: develop
  image:
    repository: hub.toibit.dev/affiliate-products
    pullPolicy: Always
    tag: "latest"
  infisical_project_id: "782efada-f435-4cd6-a020-827d9226c5c6"
  imagePullSecrets:
    - name: registry-affiliate-products-v2
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-http-prod
    host:
      client:
        host: dora.casevn.dev
        path: /
        pathType: ImplementationSpecific