global:
  env: develop
  image:
    repository: hub.viewboost.vn/affiliate-products
    pullPolicy: Always
    tag: "latest"
  infisical_project_id: "68082ae8-078e-44a5-8959-340f6219eb43"
  imagePullSecrets:
    - name: registry-affiliate-products