apiVersion: v2
name: vinfast-indonesia
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "1.16.0"
dependencies:
  - name: web-user
    version: 0.1.0
    repository: file://./charts/web-client
  - name: server-public
    version: 0.1.0
    repository: file://./charts/server-public
  - name: server-public
    version: 0.1.0
    repository: file://./charts/server-file
  - name: web-admin
    version: 0.1.0
    repository: file://./charts/web-admin
  - name: server-admin
    version: 0.1.0
    repository: file://./charts/server-admin