apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-node.fullname" . }}                 # Tên service
  labels:
    {{- include "example-node.labels" . | nindent 4 }}          # Nhãn service
spec:
  type: {{ .Values.service.type }}                              # Có 2 loại cơ bản: LoadBalancer | ClusterIP
  ports:
    - port: {{ .Values.service.port }}                          # Cổng mà service sẽ nhận request vào
      targetPort: {{ .Values.service.target_port }}             # Cổng mà các request tới được foward về.
      protocol: {{ .Values.service.protocol }}                  # Giao thức request TCP/UDP
      nodePort: {{ .Values.service.node_port }}                 # Port để kết nối external traffic trực tiếp tới service
      name: {{ .Values.service.name }}
  selector:
    {{- include "example-node.selectorLabels" . | nindent 4 }}  # Đánh nhãn cho service
