apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: "{{ .Chart.Name }}-secrets"
  annotations:
    secrets.infisical.com/debug: "true"
    kubectl.kubernetes.io/last-applied-configuration: "true"
    secrets.infisical.com/auto-reload: "true"
spec:
  hostAPI: {{ .Values.global.infisical.hostAPI }}
  resyncInterval: {{ .Values.global.infisical.resyncInterval | default 10 }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ .Values.global.infisical.projectSlug }}
        envSlug: {{ .Values.global.env }}
        recursive: false
        secretsPath: "{{ .Values.global.infisical.secretsPath }}"
      credentialsRef:
        secretName: {{ .Values.global.infisical.credentialsRef.secretName }}
        secretNamespace: {{ .Values.global.infisical.credentialsRef.secretNamespace }}
  managedSecretReference:
    secretName: "{{ .Chart.Name }}-managed-secret"
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: "Orphan"
