apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "server-admin.fullname" . }}-secrets
spec:
  hostURL: {{ .Values.global.infisical.hostURL | default "https://app.infisical.com" }}
  projectId: {{ .Values.global.infisical.projectId }}
  environment: {{ .Values.global.env }}
  tokenSecretRef:
    name: infisical-token
    key: token
  authentication:
    workspaceId: {{ .Values.global.infisical.workspaceId }}
    universalAuth:
      secretsScope:
        projectSlug: {{ .Values.global.infisical.projectSlug }} # <-- project slug
        envSlug: {{ .Values.global.env }} # "dev", "staging", "prod", etc..
        secretsPath: "{{ .Values.global.infisical.secretsPath }}" # Root is "/"
      credentialsRef:
        secretName: {{ .Values.global.infisical.credentialsRef.secretName }} # <-- name of the Kubernetes secret that stores our machine identity credentials
        secretNamespace: {{ .Values.global.infisical.credentialsRef.secretNamespace }}
  managedSecretReference:
    secretName: {{ include "server-admin.fullname" . }}-managed-secret
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: "Orphan" 