global:
  env: develop
  image:
    repository: hub.toibit.dev/affiliate-products
    pullPolicy: Always
    tag: "latest"
  infisical_project_id: "1ffa30db-eacf-452d-aa27-4d27edbb5eae"
  imagePullSecrets:
    - name: registry-affiliate-products-v2
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-http-prod
    host:
      server_admin:
        host: api.toibit.dev
        path: /user/admin
        pathType: ImplementationSpecific
      server_public:
        host: api.toibit.dev
        path: /user/app
        pathType: ImplementationSpecific
      client:
        host: user.toibit.dev
        path: /
        pathType: ImplementationSpecific
      admin:
        host: admin.toibit.dev
        path: /user
        pathType: ImplementationSpecific